//<auto-generated/>
namespace FRMJX.Core.WebServiceDomain.Models.Agency;

using System.Xml.Serialization;

// NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class BizAgiWSParam
{

	private string domainField;

	private string userNameField;

	private BizAgiWSParamCases casesField;

	/// <remarks/>
	public string domain
	{
		get
		{
			return this.domainField;
		}
		set
		{
			this.domainField = value;
		}
	}

	/// <remarks/>
	public string userName
	{
		get
		{
			return this.userNameField;
		}
		set
		{
			this.userNameField = value;
		}
	}

	/// <remarks/>
	public BizAgiWSParamCases Cases
	{
		get
		{
			return this.casesField;
		}
		set
		{
			this.casesField = value;
		}
	}

	public string ToXML()
	{
		using (var stringwriter = new System.IO.StringWriter())
		{
			var serializer = new XmlSerializer(this.GetType());
			serializer.Serialize(stringwriter, this);
			return stringwriter.ToString();
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCases
{

	private BizAgiWSParamCasesCase caseField;

	/// <remarks/>
	public BizAgiWSParamCasesCase Case
	{
		get
		{
			return this.caseField;
		}
		set
		{
			this.caseField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCase
{

	private string processField;

	private BizAgiWSParamCasesCaseEntities entitiesField;

	/// <remarks/>
	public string Process
	{
		get
		{
			return this.processField;
		}
		set
		{
			this.processField = value;
		}
	}

	/// <remarks/>
	public BizAgiWSParamCasesCaseEntities Entities
	{
		get
		{
			return this.entitiesField;
		}
		set
		{
			this.entitiesField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntities
{

	private BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicens aP_RenewalOfAgencyLicensField;

	/// <remarks/>
	public BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicens AP_RenewalOfAgencyLicens
	{
		get
		{
			return this.aP_RenewalOfAgencyLicensField;
		}
		set
		{
			this.aP_RenewalOfAgencyLicensField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicens
{

	private object nameField;

	private object familyField;

	private object nationalCodeField;

	private object agentCodeField;

	private object cellPhoneField;

	private object descriptionField;

	private object branchNameField;

	private BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckList[] ap_checklistField;

	/// <remarks/>
	public object Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public object Family
	{
		get
		{
			return this.familyField;
		}
		set
		{
			this.familyField = value;
		}
	}

	/// <remarks/>
	public object nationalCode
	{
		get
		{
			return this.nationalCodeField;
		}
		set
		{
			this.nationalCodeField = value;
		}
	}

	/// <remarks/>
	public object agentCode
	{
		get
		{
			return this.agentCodeField;
		}
		set
		{
			this.agentCodeField = value;
		}
	}

	/// <remarks/>
	public object cellPhone
	{
		get
		{
			return this.cellPhoneField;
		}
		set
		{
			this.cellPhoneField = value;
		}
	}

	/// <remarks/>
	public object Description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}

	/// <remarks/>
	public object BranchName
	{
		get
		{
			return this.branchNameField;
		}
		set
		{
			this.branchNameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("AP_CheckList", IsNullable = false)]
	public BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckList[] ap_checklist
	{
		get
		{
			return this.ap_checklistField;
		}
		set
		{
			this.ap_checklistField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckList
{

	private uint docTypeField;

	private BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckListAttachFile attachFileField;

	/// <remarks/>
	public uint DocType
	{
		get
		{
			return this.docTypeField;
		}
		set
		{
			this.docTypeField = value;
		}
	}

	/// <remarks/>
	public BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckListAttachFile AttachFile
	{
		get
		{
			return this.attachFileField;
		}
		set
		{
			this.attachFileField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckListAttachFile
{

	private BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckListAttachFileFile fileField;

	/// <remarks/>
	public BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckListAttachFileFile File
	{
		get
		{
			return this.fileField;
		}
		set
		{
			this.fileField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesAP_RenewalOfAgencyLicensAP_CheckListAttachFileFile
{

	private string fileNameField;

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string fileName
	{
		get
		{
			return this.fileNameField;
		}
		set
		{
			this.fileNameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

