//<auto-generated/>
namespace FRMJX.Core.WebServiceDomain.Models.Joinus;

using System.Xml.Serialization;

// NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class BizAgiWSParam
{

	private string domainField;

	private string userNameField;

	private BizAgiWSParamCases casesField;

	/// <remarks/>
	public string domain
	{
		get
		{
			return this.domainField;
		}
		set
		{
			this.domainField = value;
		}
	}

	/// <remarks/>
	public string userName
	{
		get
		{
			return this.userNameField;
		}
		set
		{
			this.userNameField = value;
		}
	}

	/// <remarks/>
	public BizAgiWSParamCases Cases
	{
		get
		{
			return this.casesField;
		}
		set
		{
			this.casesField = value;
		}
	}

	public string ToXML()
	{
		using (var stringwriter = new System.IO.StringWriter())
		{
			var serializer = new XmlSerializer(this.GetType());
			serializer.Serialize(stringwriter, this);
			return stringwriter.ToString();
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCases
{

	private BizAgiWSParamCasesCase caseField;

	/// <remarks/>
	public BizAgiWSParamCasesCase Case
	{
		get
		{
			return this.caseField;
		}
		set
		{
			this.caseField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCase
{

	private string processField;

	private BizAgiWSParamCasesCaseEntities entitiesField;

	/// <remarks/>
	public string Process
	{
		get
		{
			return this.processField;
		}
		set
		{
			this.processField = value;
		}
	}

	/// <remarks/>
	public BizAgiWSParamCasesCaseEntities Entities
	{
		get
		{
			return this.entitiesField;
		}
		set
		{
			this.entitiesField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntities
{

	private BizAgiWSParamCasesCaseEntitiesHR_JobRequest hR_JobRequestField;

	/// <remarks/>
	public BizAgiWSParamCasesCaseEntitiesHR_JobRequest HR_JobRequest
	{
		get
		{
			return this.hR_JobRequestField;
		}
		set
		{
			this.hR_JobRequestField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesHR_JobRequest
{

	private string nameField;

	private string familyField;

	private int genderField;

	private string fathersnameField;

	private string nationaIDField;

	private string identificationcardnumberField;

	private int provinceofbirthField;

	private int placeofbirthField;

	private int provinceofresidenceField;

	private int cityofresidenceField;

	private System.DateTime birthdayField;

	private int marriageStatusField;

	private string eMailField;

	private string telephoneField;

	private string addressField;

	private string cellphoneNumberField;

	private BizAgiWSParamCasesCaseEntitiesHR_JobRequestEdu[] eduField;

	private BizAgiWSParamCasesCaseEntitiesHR_JobRequestSkills[] skillsField;

	private BizAgiWSParamCasesCaseEntitiesHR_JobRequestJobshistory[] jobshistoryField;

	private BizAgiWSParamCasesCaseEntitiesHR_JobRequestJobList[] jobListField;

	private BizAgiWSParamCasesCaseEntitiesHR_JobRequestOfficialresume officialresumeField;

	/// <remarks/>
	public string Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string Family
	{
		get
		{
			return this.familyField;
		}
		set
		{
			this.familyField = value;
		}
	}

	/// <remarks/>
	public int Gender
	{
		get
		{
			return this.genderField;
		}
		set
		{
			this.genderField = value;
		}
	}

	/// <remarks/>
	public string Fathersname
	{
		get
		{
			return this.fathersnameField;
		}
		set
		{
			this.fathersnameField = value;
		}
	}

	/// <remarks/>
	public string NationaID
	{
		get
		{
			return this.nationaIDField;
		}
		set
		{
			this.nationaIDField = value;
		}
	}

	/// <remarks/>
	public string Identificationcardnumber
	{
		get
		{
			return this.identificationcardnumberField;
		}
		set
		{
			this.identificationcardnumberField = value;
		}
	}

	/// <remarks/>
	public int Provinceofbirth
	{
		get
		{
			return this.provinceofbirthField;
		}
		set
		{
			this.provinceofbirthField = value;
		}
	}

	/// <remarks/>
	public int Placeofbirth
	{
		get
		{
			return this.placeofbirthField;
		}
		set
		{
			this.placeofbirthField = value;
		}
	}

	/// <remarks/>
	public int Provinceofresidence
	{
		get
		{
			return this.provinceofresidenceField;
		}
		set
		{
			this.provinceofresidenceField = value;
		}
	}

	/// <remarks/>
	public int Cityofresidence
	{
		get
		{
			return this.cityofresidenceField;
		}
		set
		{
			this.cityofresidenceField = value;
		}
	}

	/// <remarks/>
	public System.DateTime Birthday
	{
		get
		{
			return this.birthdayField;
		}
		set
		{
			this.birthdayField = value;
		}
	}

	/// <remarks/>
	public int MarriageStatus
	{
		get
		{
			return this.marriageStatusField;
		}
		set
		{
			this.marriageStatusField = value;
		}
	}

	/// <remarks/>
	public string eMail
	{
		get
		{
			return this.eMailField;
		}
		set
		{
			this.eMailField = value;
		}
	}

	/// <remarks/>
	public string Telephone
	{
		get
		{
			return this.telephoneField;
		}
		set
		{
			this.telephoneField = value;
		}
	}

	/// <remarks/>
	public string Address
	{
		get
		{
			return this.addressField;
		}
		set
		{
			this.addressField = value;
		}
	}

	/// <remarks/>
	public string CellphoneNumber
	{
		get
		{
			return this.cellphoneNumberField;
		}
		set
		{
			this.cellphoneNumberField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("edu", IsNullable = false)]
	public BizAgiWSParamCasesCaseEntitiesHR_JobRequestEdu[] Edu
	{
		get
		{
			return this.eduField;
		}
		set
		{
			this.eduField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("skills", IsNullable = false)]
	public BizAgiWSParamCasesCaseEntitiesHR_JobRequestSkills[] Skills
	{
		get
		{
			return this.skillsField;
		}
		set
		{
			this.skillsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("jobshistory", IsNullable = false)]
	public BizAgiWSParamCasesCaseEntitiesHR_JobRequestJobshistory[] Jobshistory
	{
		get
		{
			return this.jobshistoryField;
		}
		set
		{
			this.jobshistoryField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("jobList", IsNullable = false)]
	public BizAgiWSParamCasesCaseEntitiesHR_JobRequestJobList[] JobList
	{
		get
		{
			return this.jobListField;
		}
		set
		{
			this.jobListField = value;
		}
	}

	/// <remarks/>
	public BizAgiWSParamCasesCaseEntitiesHR_JobRequestOfficialresume Officialresume
	{
		get
		{
			return this.officialresumeField;
		}
		set
		{
			this.officialresumeField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesHR_JobRequestEdu
{

	private string thelasteducationalcertiField;

	private string nameofplaceofstudyField;

	private string fieldofstudyField;

	private object rateofgradeField;

	private object provinceofstudyField;

	private object cityofstudyField;

	/// <remarks/>
	public string Thelasteducationalcerti
	{
		get
		{
			return this.thelasteducationalcertiField;
		}
		set
		{
			this.thelasteducationalcertiField = value;
		}
	}

	/// <remarks/>
	public string Nameofplaceofstudy
	{
		get
		{
			return this.nameofplaceofstudyField;
		}
		set
		{
			this.nameofplaceofstudyField = value;
		}
	}

	/// <remarks/>
	public string Fieldofstudy
	{
		get
		{
			return this.fieldofstudyField;
		}
		set
		{
			this.fieldofstudyField = value;
		}
	}

	/// <remarks/>
	public object Rateofgrade
	{
		get
		{
			return this.rateofgradeField;
		}
		set
		{
			this.rateofgradeField = value;
		}
	}

	/// <remarks/>
	public object Provinceofstudy
	{
		get
		{
			return this.provinceofstudyField;
		}
		set
		{
			this.provinceofstudyField = value;
		}
	}

	/// <remarks/>
	public object Cityofstudy
	{
		get
		{
			return this.cityofstudyField;
		}
		set
		{
			this.cityofstudyField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesHR_JobRequestSkills
{

	private string skillsNameField;

	private int skilllevelField;

	/// <remarks/>
	public string SkillsName
	{
		get
		{
			return this.skillsNameField;
		}
		set
		{
			this.skillsNameField = value;
		}
	}

	/// <remarks/>
	public int Skilllevel
	{
		get
		{
			return this.skilllevelField;
		}
		set
		{
			this.skilllevelField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesHR_JobRequestJobshistory
{

	private string lastworkplaceField;

	private string activitytypeField;

	private string telephonscompanyField;

	private System.DateTime startdateofjobField;

	private System.DateTime enddateofjobField;

	/// <remarks/>
	public string Lastworkplace
	{
		get
		{
			return this.lastworkplaceField;
		}
		set
		{
			this.lastworkplaceField = value;
		}
	}

	/// <remarks/>
	public string Activitytype
	{
		get
		{
			return this.activitytypeField;
		}
		set
		{
			this.activitytypeField = value;
		}
	}

	/// <remarks/>
	public string Telephonscompany
	{
		get
		{
			return this.telephonscompanyField;
		}
		set
		{
			this.telephonscompanyField = value;
		}
	}

	/// <remarks/>
	public System.DateTime Startdateofjob
	{
		get
		{
			return this.startdateofjobField;
		}
		set
		{
			this.startdateofjobField = value;
		}
	}

	/// <remarks/>
	public System.DateTime Enddateofjob
	{
		get
		{
			return this.enddateofjobField;
		}
		set
		{
			this.enddateofjobField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesHR_JobRequestJobList
{

	private int jBCAT_Level1Field;

	private int jBCAT_Level2Field;

	/// <remarks/>
	public int JBCAT_Level1
	{
		get
		{
			return this.jBCAT_Level1Field;
		}
		set
		{
			this.jBCAT_Level1Field = value;
		}
	}

	/// <remarks/>
	public int JBCAT_Level2
	{
		get
		{
			return this.jBCAT_Level2Field;
		}
		set
		{
			this.jBCAT_Level2Field = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesHR_JobRequestOfficialresume
{

	private BizAgiWSParamCasesCaseEntitiesHR_JobRequestOfficialresumeFile fileField;

	/// <remarks/>
	public BizAgiWSParamCasesCaseEntitiesHR_JobRequestOfficialresumeFile File
	{
		get
		{
			return this.fileField;
		}
		set
		{
			this.fileField = value;
		}
	}
}

/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class BizAgiWSParamCasesCaseEntitiesHR_JobRequestOfficialresumeFile
{

	private string fileNameField;

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string fileName
	{
		get
		{
			return this.fileNameField;
		}
		set
		{
			this.fileNameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

