//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FRMJX.Infrastructure.Migrations
{
    public partial class updatetables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "AboutUsSlider",
                schema: "CmsDomain",
                table: "SliderItems",
                type: "bit",
                nullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "JobPositionId",
                schema: "CmsDomain",
                table: "Employees",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AboutUsSlider",
                schema: "CmsDomain",
                table: "SliderItems");

            migrationBuilder.AlterColumn<int>(
                name: "JobPositionId",
                schema: "CmsDomain",
                table: "Employees",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);
        }
    }
}
