//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FRMJX.Infrastructure.Migrations
{
    public partial class UpdateUserFullLink : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsPersonnel",
                schema: "CmsDomain",
                table: "UsefulLinks",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsRepresention",
                schema: "CmsDomain",
                table: "UsefulLinks",
                type: "bit",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsPersonnel",
                schema: "CmsDomain",
                table: "UsefulLinks");

            migrationBuilder.DropColumn(
                name: "IsRepresention",
                schema: "CmsDomain",
                table: "UsefulLinks");
        }
    }
}
