//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FRMJX.Infrastructure.Migrations
{
    public partial class updateuserBlogPostPdf : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "ImageId",
                schema: "CmsDomain",
                table: "Pdfs",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "Email",
                schema: "CmsDomain",
                table: "Employees",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "MobileNumber",
                schema: "CmsDomain",
                table: "Employees",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "Position",
                schema: "CmsDomain",
                table: "Employees",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ImageId",
                schema: "CmsDomain",
                table: "Pdfs");

            migrationBuilder.DropColumn(
                name: "Email",
                schema: "CmsDomain",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "MobileNumber",
                schema: "CmsDomain",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "Position",
                schema: "CmsDomain",
                table: "Employees");
        }
    }
}
