//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FRMJX.Infrastructure.Migrations
{
    public partial class updatehealthCenter2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_HealthCenters_Addresses_AddressId",
                schema: "CmsDomain",
                table: "HealthCenters");

            migrationBuilder.DropIndex(
                name: "IX_HealthCenters_AddressId",
                schema: "CmsDomain",
                table: "HealthCenters");

            migrationBuilder.DropColumn(
                name: "AddressId",
                schema: "CmsDomain",
                table: "HealthCenters");

            migrationBuilder.DropColumn(
                name: "ExactAddress",
                schema: "CmsDomain",
                table: "HealthCenters");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "AddressId",
                schema: "CmsDomain",
                table: "HealthCenters",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ExactAddress",
                schema: "CmsDomain",
                table: "HealthCenters",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_HealthCenters_AddressId",
                schema: "CmsDomain",
                table: "HealthCenters",
                column: "AddressId");

            migrationBuilder.AddForeignKey(
                name: "FK_HealthCenters_Addresses_AddressId",
                schema: "CmsDomain",
                table: "HealthCenters",
                column: "AddressId",
                principalSchema: "CmsDomain",
                principalTable: "Addresses",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
