//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FRMJX.Infrastructure.Migrations
{
    public partial class updaterevelationAttribute : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "CustomFileId",
                schema: "CmsDomain",
                table: "RevelationAttributes",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "IX_RevelationAttributes_CustomFileId",
                schema: "CmsDomain",
                table: "RevelationAttributes",
                column: "CustomFileId");

            migrationBuilder.AddForeignKey(
                name: "FK_RevelationAttributes_CustomFiles_CustomFileId",
                schema: "CmsDomain",
                table: "RevelationAttributes",
                column: "CustomFileId",
                principalSchema: "CmsDomain",
                principalTable: "CustomFiles",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RevelationAttributes_CustomFiles_CustomFileId",
                schema: "CmsDomain",
                table: "RevelationAttributes");

            migrationBuilder.DropIndex(
                name: "IX_RevelationAttributes_CustomFileId",
                schema: "CmsDomain",
                table: "RevelationAttributes");

            migrationBuilder.DropColumn(
                name: "CustomFileId",
                schema: "CmsDomain",
                table: "RevelationAttributes");
        }
    }
}
